---
abstract: 'A DNS ad filter'
author:
  - 'David Watson <dwatson@cpan.org>'
build_requires:
  Data::Dumper: 0
  Net::DNS::Resolver: 0
  Test: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300015, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-DNS-Dynamic-Adfilter
requires:
  LWP::Simple: 6.00
  Moose: 2.0403
  Net::Address::IP::Local: v0.1.2
  Net::DNS::Dynamic::Proxyserver: 1.2
resources:
  bugtracker: https://github.com/terminalfool/Net-DNS-Dynamic-Adfilter/issues
  repository: git://github.com/terminalfool/Net-DNS-Dynamic-Adfilter.git
version: 0.063
